handler-expression: |
  [
    {
      "action": "modify",
      "jsonpath": "$.comment",
      "value": "#{'T(Math).random()'}"
    },
    {
      "action": "addKey",
      "jsonpath": "$.header",
      "key": "appId",
      "value": "#{aliPayConfigService.getAlipayConfig()}"
    },
    {
      "action": "addKey",
      "jsonpath": "$.header",
      "key": "modified",
      "value": "#newStringParam"
    },
    {
      "action": "addItem",
      "jsonpath": "$.header.category",
      "value": "#{'MySelfCategory'}"
    },
    {
      "action": "addJsonItem",
      "jsonpath": "$.body.book",
      "value": {
        "author": "Smith",
        "price": 9.99,
        "category": "reference",
        "title": "demo"
      }
    }
  ]

alipay:
  config:
    appId: MyDefinedAppId